[package]
name = "generate-new-address"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bdk = "0.14.0"
jni = "0.14.0"

[lib]
crate_type = ["cdylib"]
